default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  port: <%= ENV.fetch('DATABASE_PORT') { 5432 } %>
  host: <%= ENV.fetch('DATABASE_HOST') { 'localhost' } %>
  username: <%= ENV.fetch('DATABASE_USER') { 'root' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { 'password' } %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: cando_development

test:
  <<: *default
  database: cando_test

production:
  <<: *default
  database: cando_production
  username: cando
  password: <%= ENV['appname_DATABASE_PASSWORD'] %>
