default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cando_development

test:
  <<: *default
  database: cando_test

production:
  <<: *default
  database: cando_production
  username: cando
  password: <%= ENV['appname_DATABASE_PASSWORD'] %>
